---
- name: dat ip cho loobpack
  hosts: all # tên của thiết bị trong Ansible server( vì ở đây chỉ có router nên có thể để all)
# các tác vụ
  tasks:
    - name: Set loopback IPv4 address # Đặt tên task để quản lý
      ios_l3_interface: # do cấu hình router nên bắt buộc khai báo như vậy
        name: loopback 2 # tên cổng
        ipv4: 10.0.2.1/24 # địa chỉ IP của loopback

    - name: Set Ethernet0/1 IPv4 address
      ios_l3_interface:
        name: Ethernet0/2
        ipv4: 192.168.12.2/24
    - name: no shut
      ios_interface:
        name: Ethernet0/2
        state: present
    #Xem lại tất cả các cổng
    - name: Show ip
      ios_command: # Viết lệnh để gửi ở mode command line của router
        commands:
          - show ip int brief
      register: show_ip # gắn kết quả vào biến show_ip

    - debug: var=show_ip.stdout_lines # debug: in ra màn hình, đặt biến var(lấy thông tin của các dòng từ show_ip gắn vào),in biến var
